---

- name: run the playbook tasks on the localhost
  hosts: 127.0.0.1
  connection: local
  become: yes
  roles:
          - updateSystem
          - swapOff
          - aptArchives
          - system
          - desktop
          - java9-Oracle
          - chrome
          - vpn
          - ssh
          - gnome-shell
            #- teamviewer
          - skype


