---
- name: Install list of packages
  apt: name={{item}} state=present
  with_items:
          - aptitude
          - ppa-purge
          - intel-microcode
          - htop
          - preload
          - deborphan
          - indicator-multiload
          - gparted

